# Step 1 - Experimenting with Text files
The model we will be using for this 1st section is called a [Bigram](https://web.stanford.edu/~jurafsky/slp3/3.pdf) model which is a type of Natural language processing (NLP) model that predicts a word based on the immediately preceding word. 


Text file used is the book Wizard of OZ which you can download from Gutenberg library for free.
<br>Click link and make sure you select "Plain Text UTF-8"
<br>https://www.gutenberg.org/ebooks/22566



In [1]:
# Bring in text file "Wizard of OZ"
with open('data/wizard_of_oz.txt', 'r', encoding='utf=8') as f:
  text = f.read()
# print(text[:200])
# bring in all our uniqye text characters as a set and sort
chars = sorted(set(text))
vocab_size = len(chars)
print(chars)
print(len(chars)) # 81 unique character values

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
79


### Pytorch - Deep Learning framework used to train neural networks
Will allow us to train our model with GPU CUDA tensors 
https://pytorch.org/tutorials/beginner/basics/intro.html


In [2]:
# Check if GPU CUDA is enabled otherwise use CPU 
import torch
import torch.nn as nn
from torch.nn import functional as F

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


### Speed Comparison - Pytorch Tensors vs Numpy Arrays for working with multidimensional data

In [3]:
# Speed Check - Pytorch Cuda on GPU vs Numpy on CPU
import time
import numpy as np

torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'Pytorch CUDA: {elapsed_time:.8f}s')

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f'Numpy: {elapsed_time:.8f}s')

Pytorch CUDA: 0.03200436s
Numpy: 0.15499735s


### Tokenizing our text w Encoders and Decoders 
After gathering all the unique characters in our text we will need to convert these values into tokens. For this we need Encoders and Decoders <br>
**Encoders**: Converts our text values into integers (makes it machine readable)<br>
**Decoders**: Converts our integers into text values (makes it human readable after our model completes it's training)

https://www.datacamp.com/blog/what-is-tokenization#:~:text=Imagine%20you%27re%20trying,the%20two%20contexts.


In [4]:
# Encoder and Decoder logic
string_to_int = { ch:i for i, ch in enumerate(chars) }
int_to_string = { i:ch for i, ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

# encoded_hello = encode('hello')
# decoded_hello = decode(encoded_hello)
# print(f'Encoded hello =', encoded_hello)
# print(f'Decoded hello =', decoded_hello)

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([78,  1,  1, 27, 38, 41, 38, 43, 31, 47,  1, 24, 37, 27,  1, 43, 31, 28,
         1, 46, 32, 48, 24, 41, 27,  1, 38, 29,  1, 38, 48,  0,  0,  1,  1, 25,
        47,  0,  0,  1,  1, 35, 10,  1, 29, 41, 24, 37, 34,  1, 25, 24, 44, 36,
         0,  0,  1,  1, 24, 44, 43, 31, 38, 41,  1, 38, 29,  1, 43, 31, 28,  1,
        46, 32, 48, 24, 41, 27,  1, 38, 29,  1, 38, 48,  8,  1, 43, 31, 28,  1,
        35, 24, 37, 27,  1, 38, 29,  1, 38, 48])


### Grouping our characters now integers into block sizes then chunking our blocks into batch sizes
After converting our text characters into integers we want to group our values into blocks then we group those blocks into batch sizes
Think of blocks as words and batches as multiple words strung together

In [7]:
# Create block size, think of this as the words we want to be chunked together
block_size = 8
batch_size = 4

n = int(0.8*len(data))
train_data = data[:n]
test_data = data[n:]

x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print('When input is', context, 'prediction is', target)

When input is tensor([78]) prediction is tensor(1)
When input is tensor([78,  1]) prediction is tensor(1)
When input is tensor([78,  1,  1]) prediction is tensor(27)
When input is tensor([78,  1,  1, 27]) prediction is tensor(38)
When input is tensor([78,  1,  1, 27, 38]) prediction is tensor(41)
When input is tensor([78,  1,  1, 27, 38, 41]) prediction is tensor(38)
When input is tensor([78,  1,  1, 27, 38, 41, 38]) prediction is tensor(43)
When input is tensor([78,  1,  1, 27, 38, 41, 38, 43]) prediction is tensor(31)


### Create a train/test split (80/20)
We will divide our data into two parts: 80% of the data will be used for training our model and 20% of the data will be used for testing, which is data unseen to our model.<br>
https://builtin.com/data-science/train-test-split

In [9]:
# 80/20 Split
# n = int(0.8*len(data))
# train_data = data[:n]
# test_data = data[n:]

def get_batch(split):
  data = train_data if split == 'train' else test_data
  ix = torch.randint(len(data) - block_size, (batch_size,))
  print(ix)
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  x, y = x.to(device), y.to(device)
  return x, y

x, y = get_batch('train')
print('inputs: ')
print(x)
print('Predictions: ')
print(y)

tensor([ 36114, 128057,  39313,  39206])
inputs: 
tensor([[56, 52, 69, 71, 59,  1, 54, 63],
        [63, 56,  1, 64, 52, 65,  5, 70],
        [60, 63, 63,  1, 70, 71, 66, 67],
        [62, 56,  1, 76, 66, 72,  1, 71]], device='cuda:0')
Predictions: 
tensor([[52, 69, 71, 59,  1, 54, 63, 66],
        [56,  1, 64, 52, 65,  5, 70,  1],
        [63, 63,  1, 70, 71, 66, 67,  1],
        [56,  1, 76, 66, 72,  1, 71, 59]], device='cuda:0')


### Creating our Bi-gram model and defining a Forward pass function
Forward Pass - This process involves passing input data through set of layers called neural nets and applying math transformations (using weights, bias, activation functions) that help our model learn and identify patterns or relationships in the data.

In [10]:
class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embeddings_table = nn.Embedding(vocab_size, vocab_size)

  def forward_pass(self, index, targets):
    logits = self.token_embeddings_table(index)
    # B = batches, T = targets, C = channels
    B, T, C = logits.shape
    logits = logits.view(B*T, C)
    targets = targets.view(B*T)
    loss = F.cross_entropy(logits, targets)

    return logits

### Probability dstribution of next-token predictions for English characters<br>
<img src="data/next-token_probability_distribution.jpg">