## **Tensor Handling in Pytorch - Quickstart**

In [17]:
# Tensor handling in Pytorch
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [18]:
random = torch.randint(-100, 100, (6,))
random

tensor([ 38,  97,  17, -11, -82, -24])

In [19]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [20]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones(2,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [24]:
linspace = torch.linspace(3,10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [25]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [26]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [27]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
import time
import numpy as np

start_time = time.time()
#matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

0.00000000


In [29]:
# Speed Check - Pytorch Cuda on GPU vs Numpy on CPU
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'Pytorch CUDA: {elapsed_time:.8f}s')

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f'Numpy: {elapsed_time:.8f}s')

Pytorch CUDA: 0.02601290s
Numpy: 0.21730304s


In [30]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [32]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [33]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [35]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [36]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 8])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 8]])

In [43]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
# print(linear(sample))
linear(sample)

tensor([ 4.3443, -5.7759, -2.7882], grad_fn=<SqueezeBackward4>)

In [40]:
import torch.nn.functional as F

#create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [45]:
# Initialize an embedding LAyer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

#Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output)
embedded_output.shape

tensor([[-0.8382, -1.0694, -1.5856, -1.8998, -0.1643, -0.7378],
        [ 1.8377, -0.5080, -1.3874, -0.3943, -0.4452,  0.7161],
        [-0.4043,  0.3075,  0.0654,  1.6905, -0.0171,  0.4534],
        [-0.9402,  0.8379,  0.5873, -1.7946, -1.3527,  1.4594]],
       grad_fn=<EmbeddingBackward0>)


torch.Size([4, 6])

In [46]:
a = torch.tensor([[1, 2], [3, 4], [5,6]])
b = torch.tensor([[7, 8, 9], [10, 11,12]])
a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])